import * as schema from "./schema";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
const client = neon(process.env.DB_URL!);
export const db = drizzle({ client: client, schema });
// import * as schema from './schema';
// import { drizzle } from "drizzle-orm/node-postgres";
// import { Pool } from "pg";
// const pool = new Pool({ connectionString: process.env.DB_URL!});
// export const db = drizzle({ client: pool, schema });
