/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ApplyIdRouteImport } from './routes/apply/$id'
import { Route as ProgramsIdIndexRouteImport } from './routes/programs/$id/index'
import { Route as ProgramsIdApplyRouteImport } from './routes/programs/$id/apply'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdIndexRoute = ProgramsIdIndexRouteImport.update({
  id: '/programs/$id/',
  path: '/programs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdApplyRoute = ProgramsIdApplyRouteImport.update({
  id: '/programs/$id/apply',
  path: '/programs/$id/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/vote': typeof VoteRoute
  '/apply/$id': typeof ApplyIdRoute
  '/programs': typeof ProgramsIndexRoute
  '/programs/$id/apply': typeof ProgramsIdApplyRoute
  '/programs/$id': typeof ProgramsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/vote': typeof VoteRoute
  '/apply/$id': typeof ApplyIdRoute
  '/programs': typeof ProgramsIndexRoute
  '/programs/$id/apply': typeof ProgramsIdApplyRoute
  '/programs/$id': typeof ProgramsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/vote': typeof VoteRoute
  '/apply/$id': typeof ApplyIdRoute
  '/programs/': typeof ProgramsIndexRoute
  '/programs/$id/apply': typeof ProgramsIdApplyRoute
  '/programs/$id/': typeof ProgramsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/disputes'
    | '/scholarships'
    | '/vote'
    | '/apply/$id'
    | '/programs'
    | '/programs/$id/apply'
    | '/programs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/disputes'
    | '/scholarships'
    | '/vote'
    | '/apply/$id'
    | '/programs'
    | '/programs/$id/apply'
    | '/programs/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/disputes'
    | '/scholarships'
    | '/vote'
    | '/apply/$id'
    | '/programs/'
    | '/programs/$id/apply'
    | '/programs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DisputesRoute: typeof DisputesRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  VoteRoute: typeof VoteRoute
  ApplyIdRoute: typeof ApplyIdRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ProgramsIdApplyRoute: typeof ProgramsIdApplyRoute
  ProgramsIdIndexRoute: typeof ProgramsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id/': {
      id: '/programs/$id/'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id/apply': {
      id: '/programs/$id/apply'
      path: '/programs/$id/apply'
      fullPath: '/programs/$id/apply'
      preLoaderRoute: typeof ProgramsIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DisputesRoute: DisputesRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  VoteRoute: VoteRoute,
  ApplyIdRoute: ApplyIdRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ProgramsIdApplyRoute: ProgramsIdApplyRoute,
  ProgramsIdIndexRoute: ProgramsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
