/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships/index'
import { Route as ScholarshipsIdApplicantSubmitRouteImport } from './routes/scholarships/$id.applicant-submit'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIdApplicantSubmitRoute =
  ScholarshipsIdApplicantSubmitRouteImport.update({
    id: '/scholarships/$id/applicant-submit',
    path: '/scholarships/$id/applicant-submit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/vote': typeof VoteRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/scholarships/$id/applicant-submit': typeof ScholarshipsIdApplicantSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/vote': typeof VoteRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/scholarships/$id/applicant-submit': typeof ScholarshipsIdApplicantSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/vote': typeof VoteRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/scholarships/$id/applicant-submit': typeof ScholarshipsIdApplicantSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/vote'
    | '/scholarships'
    | '/scholarships/$id/applicant-submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/vote'
    | '/scholarships'
    | '/scholarships/$id/applicant-submit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/vote'
    | '/scholarships/'
    | '/scholarships/$id/applicant-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  VoteRoute: typeof VoteRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  ScholarshipsIdApplicantSubmitRoute: typeof ScholarshipsIdApplicantSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$id/applicant-submit': {
      id: '/scholarships/$id/applicant-submit'
      path: '/scholarships/$id/applicant-submit'
      fullPath: '/scholarships/$id/applicant-submit'
      preLoaderRoute: typeof ScholarshipsIdApplicantSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  VoteRoute: VoteRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  ScholarshipsIdApplicantSubmitRoute: ScholarshipsIdApplicantSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
