// Auto-generated by sync-deployments.mjs — do not edit manually
export const milestoneManagerAbi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyActed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CommitteeNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DisputeWindowOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientProgramFund",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitialization",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotBountyRole",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotCommittee",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotCore",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInitializing",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OptionalDisabled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Reentrancy",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScholarNotActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TooManyMandatory",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TooManyOptional",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "enum ScholarshipTypes.MilestoneStatus",
        "name": "got",
        "type": "uint8"
      }
    ],
    "name": "WrongStatus",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "Initialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "approvedBy",
        "type": "address"
      }
    ],
    "name": "MilestoneApproved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "MilestoneCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum ScholarshipTypes.MilestoneKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "MilestoneCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "MilestoneFrozen",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum ScholarshipTypes.MilestoneKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "MilestoneProposed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "rejectedBy",
        "type": "address"
      }
    ],
    "name": "MilestoneRejected",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "MilestoneReleased",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      }
    ],
    "name": "MilestoneSubmitted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "admin",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "approveMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "core",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256[]",
        "name": "amounts",
        "type": "uint256[]"
      },
      {
        "internalType": "string[]",
        "name": "descs",
        "type": "string[]"
      }
    ],
    "name": "createMandatoryBatch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "executeMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "forceCompleteMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "freezeMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "getMandatoryIds",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getMilestone",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "programId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "scholar",
            "type": "address"
          },
          {
            "internalType": "enum ScholarshipTypes.MilestoneKind",
            "name": "kind",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "proposedBy",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "approvedBy",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "descriptionCID",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "proofCID",
            "type": "string"
          },
          {
            "internalType": "enum ScholarshipTypes.MilestoneStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint48",
            "name": "submittedAt",
            "type": "uint48"
          },
          {
            "internalType": "uint48",
            "name": "disputeDeadline",
            "type": "uint48"
          },
          {
            "internalType": "uint48",
            "name": "completedAt",
            "type": "uint48"
          }
        ],
        "internalType": "struct ScholarshipTypes.Milestone",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "getOptionalIds",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_admin",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "coreAddr",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "treasuryAddr",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "mandatoryIds",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "milestoneOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "milestones",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "enum ScholarshipTypes.MilestoneKind",
        "name": "kind",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "proposedBy",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "approvedBy",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "descriptionCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      },
      {
        "internalType": "enum ScholarshipTypes.MilestoneStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "uint48",
        "name": "submittedAt",
        "type": "uint48"
      },
      {
        "internalType": "uint48",
        "name": "disputeDeadline",
        "type": "uint48"
      },
      {
        "internalType": "uint48",
        "name": "completedAt",
        "type": "uint48"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "optionalIds",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "programCommittee",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "enum ScholarshipTypes.MilestoneKind",
        "name": "kind",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "descriptionCID",
        "type": "string"
      }
    ],
    "name": "proposeMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "rejectMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "releaseMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "coreAddr",
        "type": "address"
      }
    ],
    "name": "setCore",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "committeeContract",
        "type": "address"
      }
    ],
    "name": "setProgramCommittee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      }
    ],
    "name": "submitProof",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
