// Auto-generated by sync-deployments.mjs — do not edit manually
export const scholarshipBountyAbi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AccessControlBadConfirmation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "neededRole",
        "type": "bytes32"
      }
    ],
    "name": "AccessControlUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "AddressEmptyCode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BHHasActiveDispute",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "cooldownUntil",
        "type": "uint256"
      }
    ],
    "name": "BHOnCooldown",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CounterEvidenceRequired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DefenseWindowExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DefenseWindowStillOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DisputeAlreadyResolved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DisputeNotFound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "ERC1967InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC1967NonPayable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FailedCall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitialization",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInitializing",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotScholar",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScholarAlreadyDisputed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScholarNotActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UUPSUnauthorizedCallContext",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "slot",
        "type": "bytes32"
      }
    ],
    "name": "UUPSUnsupportedProxiableUUID",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "bountyHunter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "cooldownUntil",
        "type": "uint256"
      }
    ],
    "name": "BHFlagged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "DisputeAutoGuilty",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "pid",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "bountyHunter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum ScholarshipTypes.DisputeType",
        "name": "disputeType",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "evidenceCID",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "stake",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "potentialReward",
        "type": "uint256"
      }
    ],
    "name": "DisputeRaised",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "bountyHunterWon",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "bhReward",
        "type": "uint256"
      }
    ],
    "name": "DisputeResolved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "ForfeitedStakesWithdrawn",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "originalStake",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "appliedStake",
        "type": "uint256"
      }
    ],
    "name": "GriefingStakeApplied",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "Initialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "previousAdminRole",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "newAdminRole",
        "type": "bytes32"
      }
    ],
    "name": "RoleAdminChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleGranted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "StudentConceded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "counterEvidenceCID",
        "type": "string"
      }
    ],
    "name": "StudentDefended",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "Upgraded",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "DEFAULT_ADMIN_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "RESOLVER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "UPGRADER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "UPGRADE_INTERFACE_VERSION",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "VERSION",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "activeDisputeForScholar",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "bhRecords",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "activeDisputeId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "cooldownUntil",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalWins",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalLosses",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "consecutiveLosses",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isFlagged",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "pid",
        "type": "uint256"
      }
    ],
    "name": "calculateStake",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "stakeRequired",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "potentialReward",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "concede",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "core",
    "outputs": [
      {
        "internalType": "contract IScholarshipCore",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "disputes",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "pid",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "bountyHunter",
        "type": "address"
      },
      {
        "internalType": "enum ScholarshipTypes.DisputeType",
        "name": "disputeType",
        "type": "uint8"
      },
      {
        "internalType": "enum ScholarshipTypes.DisputeStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "evidenceCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "counterEvidenceCID",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "stake",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "potentialReward",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "raisedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "defenseDeadline",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "resolvedAt",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "resolvedBy",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "bh",
        "type": "address"
      }
    ],
    "name": "getBHRecord",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "activeDisputeId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "cooldownUntil",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalWins",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalLosses",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "consecutiveLosses",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isFlagged",
            "type": "bool"
          }
        ],
        "internalType": "struct ScholarshipTypes.BountyHunterRecord",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "getDispute",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "pid",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "scholar",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "milestoneId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "bountyHunter",
            "type": "address"
          },
          {
            "internalType": "enum ScholarshipTypes.DisputeType",
            "name": "disputeType",
            "type": "uint8"
          },
          {
            "internalType": "enum ScholarshipTypes.DisputeStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "string",
            "name": "evidenceCID",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "counterEvidenceCID",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "stake",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "potentialReward",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "raisedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "defenseDeadline",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "resolvedAt",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "resolvedBy",
            "type": "address"
          }
        ],
        "internalType": "struct ScholarshipTypes.Dispute",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      }
    ],
    "name": "getRoleAdmin",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "admin",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_usdc",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_core",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_treasury",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "milestone",
    "outputs": [
      {
        "internalType": "contract IMilestoneManager",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "proxiableUUID",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "pid",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "internalType": "enum ScholarshipTypes.DisputeType",
        "name": "disputeType",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "evidenceCID",
        "type": "string"
      }
    ],
    "name": "raiseDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "callerConfirmation",
        "type": "address"
      }
    ],
    "name": "renounceRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "bountyHunterWon",
        "type": "bool"
      }
    ],
    "name": "resolveDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "counterEvidenceCID",
        "type": "string"
      }
    ],
    "name": "submitCounterEvidence",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "treasury",
    "outputs": [
      {
        "internalType": "contract IScholarshipTreasury",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "triggerAutoGuilty",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newImplementation",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "upgradeToAndCall",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "withdrawForfeitedStakes",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
