// Auto-generated by sync-deployments.mjs — do not edit manually
export const scholarshipCoreAbi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyApplied",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyDonated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ApplicantListIncomplete",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CandidateNotShortlisted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotApplyToOwnProgram",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ConfidenceStakeAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ConfidenceStakeExceedsDonation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ConfidenceStakeMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DisputeWindowStillOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientDonation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientFund",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientVotingPower",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCandidateRange",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitialization",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "enum ScholarshipTypes.ProgramStatus",
        "name": "expected",
        "type": "uint8"
      },
      {
        "internalType": "enum ScholarshipTypes.ProgramStatus",
        "name": "actual",
        "type": "uint8"
      }
    ],
    "name": "InvalidProgramStatus",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidScoreWeights",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSlashDistribution",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSortOrder",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTimeline",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxRetriesExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MilestoneNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MilestoneNotInDisputeWindow",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "MissingRole",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MustVoteBeforeStaking",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAdmin",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInitializing",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotMilestoneOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OnlyInitiator",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProgramNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "QuorumNotMet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Reentrancy",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScholarNotActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StudentBlacklisted",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "freezeUntil",
        "type": "uint256"
      }
    ],
    "name": "StudentFrozen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TargetWinnersExceedsMax",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TooEarly",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VotingNotEnded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VotingPowerLocked",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "committeeContract",
        "type": "address"
      }
    ],
    "name": "CommitteeAssigned",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "ConfidenceStaked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "donor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "grossAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "netAmount",
        "type": "uint256"
      }
    ],
    "name": "DonationReceived",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "version",
        "type": "uint64"
      }
    ],
    "name": "Initialized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "MilestoneCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "MilestoneFrozen",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "MilestoneReleased",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      }
    ],
    "name": "MilestoneSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      }
    ],
    "name": "ProgramCancelled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      }
    ],
    "name": "ProgramCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "initiator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "metadataCID",
        "type": "string"
      }
    ],
    "name": "ProgramCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum ScholarshipTypes.ProgramStatus",
        "name": "newStatus",
        "type": "uint8"
      }
    ],
    "name": "ProgramStatusChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "RoleGranted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "RoleRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "ScholarCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      }
    ],
    "name": "ScholarSelected",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum ScholarshipTypes.DisputeType",
        "name": "dtype",
        "type": "uint8"
      }
    ],
    "name": "ScholarSlashed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "totalScore",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "scoredBy",
        "type": "address"
      }
    ],
    "name": "ScoreSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "retryCount",
        "type": "uint8"
      }
    ],
    "name": "StudentApplied",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "score",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "locked",
        "type": "bool"
      }
    ],
    "name": "StudentScreenedOut",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "score",
        "type": "uint256"
      }
    ],
    "name": "StudentShortlisted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "Upgraded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "candidate",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "weight",
        "type": "uint256"
      }
    ],
    "name": "VoteCast",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "BOUNTY_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "COMMITTEE_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "UPGRADER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "VERSION",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "admin",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "applicants",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      },
      {
        "internalType": "enum ScholarshipTypes.ApplicationStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "profileCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "documentCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "essayCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "recommendCID",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "screeningScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "voteScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "scoreTimestamp",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "retryCount",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "scoreDisputed",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "profileCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "documentCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "essayCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "recommendCID",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "academicScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "incomeScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "recommendScore",
        "type": "uint256"
      }
    ],
    "name": "applyToProgram",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      }
    ],
    "name": "cancelProgram",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "metadataCID",
        "type": "string"
      },
      {
        "internalType": "enum ScholarshipTypes.EducationLevel",
        "name": "educationLevel",
        "type": "uint8"
      },
      {
        "internalType": "enum ScholarshipTypes.ScreeningMode",
        "name": "screeningMode",
        "type": "uint8"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "academicWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "incomeWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "essayWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "recommendWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "extracurricWeight",
            "type": "uint8"
          }
        ],
        "internalType": "struct ScholarshipTypes.ScoreWeights",
        "name": "weights",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "bountyHunterPercent",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "treasuryPercent",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "protocolPercent",
            "type": "uint8"
          }
        ],
        "internalType": "struct ScholarshipTypes.SlashDistribution",
        "name": "slashDist",
        "type": "tuple"
      },
      {
        "internalType": "uint8",
        "name": "maxCandidates",
        "type": "uint8"
      },
      {
        "internalType": "uint8",
        "name": "targetWinners",
        "type": "uint8"
      },
      {
        "internalType": "uint256[4]",
        "name": "timeline",
        "type": "uint256[4]"
      },
      {
        "internalType": "uint256",
        "name": "milestoneDisputeWindow",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalFund",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "committeeContract",
        "type": "address"
      }
    ],
    "name": "createProgram",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "grossAmount",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "nftMetadataURI",
        "type": "string"
      }
    ],
    "name": "donate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "donorNFT",
    "outputs": [
      {
        "internalType": "contract ICredentialNFT",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "executeMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "freezeMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getMilestone",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "programId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "scholar",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "descriptionCID",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "proofCID",
            "type": "string"
          },
          {
            "internalType": "enum ScholarshipTypes.MilestoneStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "submittedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "disputeDeadline",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "completedAt",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isFirstMilestone",
            "type": "bool"
          }
        ],
        "internalType": "struct ScholarshipTypes.Milestone",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getProgram",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "initiator",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "metadataCID",
            "type": "string"
          },
          {
            "internalType": "enum ScholarshipTypes.EducationLevel",
            "name": "educationLevel",
            "type": "uint8"
          },
          {
            "internalType": "enum ScholarshipTypes.ScreeningMode",
            "name": "screeningMode",
            "type": "uint8"
          },
          {
            "internalType": "enum ScholarshipTypes.ProgramStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "components": [
              {
                "internalType": "uint8",
                "name": "academicWeight",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "incomeWeight",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "essayWeight",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "recommendWeight",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "extracurricWeight",
                "type": "uint8"
              }
            ],
            "internalType": "struct ScholarshipTypes.ScoreWeights",
            "name": "scoreWeights",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint8",
                "name": "bountyHunterPercent",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "treasuryPercent",
                "type": "uint8"
              },
              {
                "internalType": "uint8",
                "name": "protocolPercent",
                "type": "uint8"
              }
            ],
            "internalType": "struct ScholarshipTypes.SlashDistribution",
            "name": "slashDist",
            "type": "tuple"
          },
          {
            "internalType": "uint8",
            "name": "maxCandidates",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "targetWinners",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "applicationStart",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "applicationEnd",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "votingStart",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "votingEnd",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "milestoneDisputeWindow",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalFund",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "allocatedFund",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spentFund",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "yieldAccrued",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "applicantCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "shortlistedCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "activeScholarCount",
            "type": "uint256"
          }
        ],
        "internalType": "struct ScholarshipTypes.Program",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getProgramApplicants",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getRemainingFund",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "w",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getScholar",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "programId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "wallet",
            "type": "address"
          },
          {
            "internalType": "enum ScholarshipTypes.StudentStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "freezeUntil",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isBlacklisted",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "currentMilestone",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalMilestones",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalReceived",
            "type": "uint256"
          }
        ],
        "internalType": "struct ScholarshipTypes.Scholar",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "getShortlist",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "globalFreezeUntil",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "globalStudentStatus",
    "outputs": [
      {
        "internalType": "enum ScholarshipTypes.StudentStatus",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_admin",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_usdc",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_treasury",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_reputation",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_donorNFT",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_studentNFT",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      }
    ],
    "name": "isStudentEligible",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      },
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "milestoneOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "milestones",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "descriptionCID",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      },
      {
        "internalType": "enum ScholarshipTypes.MilestoneStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "submittedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "disputeDeadline",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "completedAt",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isFirstMilestone",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      }
    ],
    "name": "openApplications",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      }
    ],
    "name": "openScreening",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "scholar",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "placeConfidenceStake",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "programCommittee",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "programs",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "initiator",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "metadataCID",
        "type": "string"
      },
      {
        "internalType": "enum ScholarshipTypes.EducationLevel",
        "name": "educationLevel",
        "type": "uint8"
      },
      {
        "internalType": "enum ScholarshipTypes.ScreeningMode",
        "name": "screeningMode",
        "type": "uint8"
      },
      {
        "internalType": "enum ScholarshipTypes.ProgramStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "academicWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "incomeWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "essayWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "recommendWeight",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "extracurricWeight",
            "type": "uint8"
          }
        ],
        "internalType": "struct ScholarshipTypes.ScoreWeights",
        "name": "scoreWeights",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "bountyHunterPercent",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "treasuryPercent",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "protocolPercent",
            "type": "uint8"
          }
        ],
        "internalType": "struct ScholarshipTypes.SlashDistribution",
        "name": "slashDist",
        "type": "tuple"
      },
      {
        "internalType": "uint8",
        "name": "maxCandidates",
        "type": "uint8"
      },
      {
        "internalType": "uint8",
        "name": "targetWinners",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "applicationStart",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "applicationEnd",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "votingStart",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "votingEnd",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "milestoneDisputeWindow",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalFund",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "allocatedFund",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "spentFund",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "yieldAccrued",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "applicantCount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "shortlistedCount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "activeScholarCount",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      }
    ],
    "name": "releaseMilestone",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reputation",
    "outputs": [
      {
        "internalType": "contract IScholarshipReputation",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "ranked",
        "type": "address[]"
      }
    ],
    "name": "resolveShortlist",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "retryCount",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "scholars",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      },
      {
        "internalType": "enum ScholarshipTypes.StudentStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "freezeUntil",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isBlacklisted",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "currentMilestone",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalMilestones",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalReceived",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "scoreComponents",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "academicScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "incomeScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "recommendScore",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isSubmitted",
        "type": "bool"
      },
      {
        "internalType": "address",
        "name": "scoredBy",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "ranked",
        "type": "address[]"
      },
      {
        "internalType": "uint256[][]",
        "name": "amounts",
        "type": "uint256[][]"
      }
    ],
    "name": "selectWinners",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "enum ScholarshipTypes.DisputeType",
        "name": "disputeType",
        "type": "uint8"
      }
    ],
    "name": "slashScholar",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "studentNFT",
    "outputs": [
      {
        "internalType": "contract ICredentialNFT",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "applicant",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "academicScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "incomeScore",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "recommendScore",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "committeeAddress",
        "type": "address"
      }
    ],
    "name": "submitCommitteeScore",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "milestoneId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "proofCID",
        "type": "string"
      }
    ],
    "name": "submitMilestoneProof",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "treasury",
    "outputs": [
      {
        "internalType": "contract IScholarshipTreasury",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newImpl",
        "type": "address"
      }
    ],
    "name": "upgradeTo",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "programId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "candidate",
        "type": "address"
      }
    ],
    "name": "voteForCandidate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "voterInfo",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "donatedAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "remainingVotingPower",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "votedFor",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "confidenceStake",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "confidenceStakeFor",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "hasClaimedYield",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
